### ISSUE TITLE
Predicitve Analysis needs added to the OpsServer install process

### ISSUE THREAD

**Issue by dfoll** [Esri/ops-server-config#762] opened 2015-05-07 16:34 UTC
Predicitve Analysis needs added to the OpsServer install process.

@kAilshie is the POC for development for Predictive Analysis. He can work with @elinz and @ACueva on this.

**Comment by ACueva** [comment] 2015-05-07 16:44
@kAilshie and I have been talking, I can assist him in what needs to be done to get this incorporated in our install process.

**Comment by ACueva** [comment] 2015-05-14 15:50
@kAilshie Let me know once you guys get closer to a finished product so I can assist you with getting your instructions into our ops server install guide.

**Comment by elinz** [comment] 2015-08-24 19:59
Closing since this is a duplicate of #853

**Closed by elinz** 2015-08-24 19:59 UTC
Labels: G - Intelligence Team, G - Release Team, Install and Publishing
