### ISSUE TITLE
Image Discovery web app does not work in Chrome

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/ops-server-config#1168] opened 2015-10-05 20:22 UTC
When you select an area, either by extent or rectangle, you get the error "There is currently no imagery available for your search area" 

![image](https://cloud.githubusercontent.com/assets/3800729/10292429/0f520da8-6b64-11e5-8ced-1ebb4ca58730.png)

**Comment by conklinbd** [comment] 2015-10-05 21:06
@lfunkhouser this error is because the arcgisonline image services are using a weak ssl certificate. I know that we logged that issue already but can't seem to locate it. @ACueva is one that figured it out.

**Comment by elinz** [comment] 2015-10-05 21:43
@conklinbd I had submitted this error to the image team who forwarded to IST. They are working on it but don't know the status. I'll find my GitHub issue.

**Comment by elinz** [comment] 2015-10-05 21:45
The issue is #1008

**Comment by conklinbd** [comment] 2015-10-06 16:57
Since this is a known issue for this release I am going to change it to next.

**Comment by elinz** [comment] 2015-12-16 14:57
@nfeuerstein issue #1008 has been resolved (i.e. issue with online SSL certificate issue). I've tested the Image Discovery app and it does work. I'll go ahead and close the issue.

**Closed by elinz** 2015-12-16 14:57 UTC
Labels: G - Intelligence Team
