### ISSUE TITLE
Change Detection Dark Object Subtraction

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#709] opened 2015-01-24 00:54 UTC
4.	The DOS tool failed to run.  Either by being called by the step or independently from the project toolbox or the github toolbox.  
![image](https://cloud.githubusercontent.com/assets/5116835/5885387/7aa69c02-a320-11e4-8f0f-27dbd9d9616c.png)

**Comment by helyx-amcmillan** [comment] 2015-01-29 16:34
One iteration of the tool had a 'Median' option which is what I chose in the model. However, this option doesn't seem to be available any more. Have changed to average. Tool should now run.

**Comment by csmoore** [comment] 2015-01-29 16:58
Just a team process thing/reminder (for everyone): when you believe you have fixed an issue assigned to you - **don't close the issue yourself** but assign to the issue originator/tester **to verify**. 

1. Add a comment such as "Fixed in commit X + assigning to @ tester to test/verify"
2. Tell them **where** the fix is to test
3. Assign to the originator to verify
4. If you like, you may create/add label(s) "fixed" "to verify" to better communicate the state
5. The tester will then verify the fix (or re-open if not)/close the issue **within a week** 
    1. If they don't verify it within a week, then anyone can close the issue with a comment "not verified"

We really want the person who opens an issue to be the same person who verifies that the same issue is fixed for them - that way we make sure there is agreement among everyone that the issue is fixed for them.

This need not apply to everything, for instance a few closed items were more obvious things like "I deleted that tool" so probably don't need an extra verification step, but the default would normally be to verify.

Additional Team Note: You should always be verifying the issues you create in a timely manner and  adding comments that explain why you closed an issue.

**Comment by csmoore** [comment] 2015-01-29 16:58
Assign to @NatalieCampos to verify

**Comment by NatalieCampos** [comment] 2015-01-30 21:08
The DOS runs but the output is wrong.  The if the input of a DOS is a 6 band image then the output should be a 6 band image. The current output is a 1 band image.  

![image](https://cloud.githubusercontent.com/assets/5116835/5983316/060ec4b2-a881-11e4-914d-021950d92381.png)

**Comment by dfoll** [comment] 2015-02-26 22:59
This issue was moved to ArcGIS/solutions-templates#18

**Closed by dfoll** 2015-02-26 22:59 UTC
Labels: Intelligence Team
