### ISSUE TITLE
PortalContentPost.py traceback error

### ISSUE THREAD

**Issue by ScottCecilio** [Esri/ops-server-config#698] opened 2015-01-13 18:19 UTC
![tracebackerror](https://cloud.githubusercontent.com/assets/6999909/5726097/a1ce70ae-9b26-11e4-95f2-c27c1a50232e.PNG)

Received the following error when trying to post content to the Portal.

**Comment by conklinbd** [comment] 2015-01-14 15:46
Scott - Can you remove that item from the content folder and try publishing again?

**Comment by ScottCecilio** [comment] 2015-01-15 02:00
afdbd188f0e1438d9e218f5245ab9d1f) from the ReleasedIntel folder the script was able to publish the remaining items for that user.  However, the script failed again when publishing (item 63acf5df2e314bbc9ee63804736585d6) to the ReleasedMilitary user. I had to rerun the script after removing this item as well from the OPSServerInstall\Portal\PortalContent\ReleasedMilitary\items folder.  This did allow me to get past this portion of the script.

Unfortunately, I got another error when the script was trying to update URL's and Item IDs


![image](https://cloud.githubusercontent.com/assets/6999909/5751350/38a494d6-9c30-11e4-82cf-6591aa467518.png)

**Comment by ScottCecilio** [comment] 2015-01-15 02:02
Once removed (item afdbd188f0e1438d9e218f5245ab9d1f) from the ReleasedIntel folder the script was able to publish the remaining items for that user.  However, the script failed again when publishing (item 63acf5df2e314bbc9ee63804736585d6) to the ReleasedMilitary user. I had to rerun the script after removing this item as well from the OPSServerInstall\Portal\PortalContent\ReleasedMilitary\items folder. This did allow me to get past this portion of the script.

Unfortunately, I got another error when the script was trying to update URL's and Item IDs

![image](https://cloud.githubusercontent.com/assets/6999909/5751370/95a0ce48-9c30-11e4-856d-a26d559c4cec.png)

**Comment by ACueva** [comment] 2015-01-23 23:33
I reviewed item 63acf5df2e314bbc9ee63804736585d6, this is Vehicle Commander.  I believe the issue is related to the size of the portal item.  In this case, the zip file VehicleCommander.tar.zip is approximately 309mb.  I have seen this issue occur when publishing to other servers and the only remedy is to remove all items containing downloads above approximately 80mb.
I replace the items above 80mb with either empty zip files and or smaller map packages.  Once everything publishes fine, I then go back and manually update the portal items.
It is very important that you use the same name as the file replaced, that way there is no issue updating the file with the correct one.

**Comment by ScottCecilio** [comment] 2015-01-28 14:18
With the help of @garys-esri we were able to get past this error.  Within the Portal we had some items owned by "esri_apps" that I was not able to delete.  Gary added some code to the script to ignore this paticular item and the script completed.  See below (inserted on line #748)

 # TODO filtering out item IDs that don't work
        if not item.get("id") == "b6da1d029f7748a3a62167f1b3638ece":
            # Replace host name/item ids in item json properties
            update_item_properties(portal, item, hostname_map, id_map)


I know this is not a fix for the item and rather just helping me get past the error.  I would still like for someone to look into what can be done to permanently fix this.

**Comment by garys-esri** [comment] 2015-01-28 15:35
The item ID we excluded, b6da1d029f7748a3a62167f1b3638ece , is for an item called Explorer for ArcGIS (Windows), owned by esri_apps. You can search and find it in the Portal. But when we click on it in the Portal, we get an error page with this message:

The item you requested cannot be found. 
The item may have been deleted or you may have entered an incorrect URL.

**Comment by ACueva** [comment] 2015-01-28 23:13
@elinz, FYI, @ScottCecilio and @garys-esri have a fix for this issue.  From what Scott told me it appears Gary was able to comment out some code pertaining to these missing items.

**Comment by elinz** [comment] 2015-01-29 03:27
I had provided Scott the Python code to work around this issue several weeks ago in an email using an "if" statement. The only way I was able to avoid the faulty out of the box installed portal item was to skip uploading this item. I still need to research if there is an alternative logic to avoid any similar issue if they exist in any future portal build.

-------- Original message --------
From: Avi Cueva
Date:01/28/2015 3:13 PM (GMT-08:00)
To: Esri/ops-server-config
Cc: Eric Linz
Subject: Re: [ops-server-config] PortalContentPost.py traceback error (#698)


@elinz<https://github.com/elinz>, FYI, @ScottCecilio<https://github.com/ScottCecilio> and @garys-esri<https://github.com/garys-esri> have a fix for this issue. From what Scott told me it appears Gary was able to comment out some code pertaining to these missing items.

**Comment by garys-esri** [comment] 2015-01-29 13:00
Thanks, Eric. In your script, did you hard-code the item ID like in Scott's script above? I wonder if there is a way to automatically detect faulty items and skip uploading them, or at least try and catch an error. I don't know if Python has try and catch, but it must have something like it. That would be a great enhancement to the script.

**Comment by elinz** [comment] 2015-01-29 19:49
Yes, Scott used the code I sent him with the hardcoded item id. Python does have a way to catch exceptions, but the problem is that the underlying python library is intercepting. I still need to research a solution.

-------- Original message --------
From: Gary Sheppard
Date:01/29/2015 5:02 AM (GMT-08:00)
To: Esri/ops-server-config
Cc: Eric Linz
Subject: Re: [ops-server-config] PortalContentPost.py traceback error (#698)


Thanks, Eric. In your script, did you hard-code the item ID like in Scott's script above? I wonder if there is a way to automatically detect faulty items and skip uploading them, or at least try and catch an error. I don't know if Python has try and catch, but it must have something like it. That would be a great enhancement to the script.

**Comment by elinz** [comment] 2015-02-09 16:39
@ScottCecilio The issues you described are two different issues. 1) The issues you encountered with the actually publishing/uploading due to default file upload limits. The Ops Server installation guide instructs users to increase a couple of portal properties which will allow these items to be published. 2) The publishing script fails when executing the update ID/URL function on item 63acf5df2e314bbc9ee63804736585d6 because there is something wrong with this built in item. I am going to create a new GitHub issue for this second issue.

**Comment by elinz** [comment] 2015-02-09 16:41
@ScottCecilio when you set up the Ops Server did you increase the portal file upload limits are described in the "Increase Portal file upload limits" section of the Ops Server Installation Guide? Thanks.

**Comment by elinz** [comment] 2015-02-09 16:45
2nd issue, issue processing invalid item capture in #695.

**Comment by ScottCecilio** [comment] 2015-02-09 23:55
@elinz I did check increase the file limits per the documentation.  I even went as far as wiping the whole machine and starting again from scratch.  This produced the same results.

**Comment by elinz** [comment] 2015-02-10 00:04
@ScottCecilio Thanks. I'll have to test again. So far I've never encountered this issue again after increasing the file limits.

**Comment by VytautasGipiskis** [comment] 2015-03-09 13:35
I had the same issue uploading large items (while portal limits were increased, even machine was restated to make sure settings are applied). Solved by replacing UrbanFeatureMaintanceMap.mpk with empty file with the same name, and including a line
 if not item.get("id") ==  "b6da1d029f7748a3a62167f1b3638ece":
as it was recommended by ScottCecilio on Jan 28.

**Comment by elinz** [comment] 2015-03-16 14:54
Fixed in latest merge.

**Closed by elinz** 2015-03-16 14:54 UTC
Labels: bug, Install and Publishing, Release Team
