### ISSUE TITLE
TEM2015 Test 02: Tsunami Damage Assessment 3D has no data

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#1322] opened 2015-10-14 21:15 UTC
The 3D scene opens to a gridded sphere - no data.  Item 4c84bc4126b7445784003e1b5c5b95b7
![image](https://cloud.githubusercontent.com/assets/3801392/10498001/12a4a760-727e-11e5-97fb-eac84a395cc6.png)

**Comment by conklinbd** [comment] 2015-10-15 14:04
This appears to have been an issue during the publish. There is no data associated with the web scene. sharing/rest/content/items/4c84bc4126b7445784003e1b5c5b95b7/data is empty.
This is the only Web Scene we are copying so this must be an issue with publishing of this text item type.

**Comment by elinz** [comment] 2015-10-15 21:52
The problem is that the portalpy module I'm using has the incorrect data type for "Web Scenes" it should be "Text/JSON", but it was defined as "File" due to incorrect information in the portal api help page for the 10.3.1 portalhelp/apidocs/rest/index.html?item.html#/Items_and_item_types/02t60000001n000000/ “Items and item types”.

**Comment by elinz** [comment] 2015-10-15 21:58
Updated the portalpy\_init_.py file. Fixed in Esri\ops-server-config v.next. Will verify after testing on TEM2015 Test 03 machine.

Added to queue for manual extraction

**Comment by conklinbd** [comment] 2015-10-16 17:50
Issue #1352 depends on this item

**Comment by elinz** [comment] 2015-10-18 03:33
Verified on TEM2015 Test 03 server. Closing issue.

![image](https://cloud.githubusercontent.com/assets/4635490/10562377/34fdda6a-750e-11e5-938b-5121d223fc3d.png)

**Closed by elinz** 2015-10-18 03:33 UTC
Labels: 3 - Verify, G - Release Team, S - Showstopper
