### ISSUE TITLE
OpsServerInstall fails when using a single PRVC file  

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#629] opened 2014-10-28 16:40 UTC
If you have a single PRVC file that contains entitlements for Server and Portal (and others), and set the values for paths to both the server and portal license in the InstallSettings.bat file to this single file, OpsServerInstall.bat fails

Mitigation was to separate the entitlements to two separate PRVC files, then the batch file ran successfully.

(discovered by Esri Italy at TEM)

**Comment by elinz** [comment] 2015-02-13 14:57
@kerryrobinson I did more testing and the problem is with the SoftwareAuthorization.exe. It only authorizes the product that is listed last in the .prvc. So for example I have a .prvc file with the entries for ArcGIS Server and it's extensions, which I edited to include portal at the end of the file. When I run the SoftwareAuthorization.exe so I can interact with the GUI I see that the product that is being authorized is Portal for ArcGIS. 

How was the .prvc file that Italy was using generated? Did they manually edit the file to include both authorization numbers for both server and portal or that was the way the file was generated by Customer Service.

I'll talk with the licensing dev team, but would like to know how this file with both number was generated before I talk with them. Thanks.

**Comment by kerryrobinson** [comment] 2015-02-13 21:30
OK, I’ll see if I can find out.

**Comment by kerryrobinson** [comment] 2015-02-17 16:03
@elinz, I checked with Gianluca and he said the PRVC file was created by the Esri customer care site, including multiple products: 

ArcGIS Server = ECPXXXXXXXXX
Portal for ArcGIS = ECPXXXXXXXXX
GeoEvent Processor Server = ECPXXXXXXXXX 
Image Server Extension = ECPXXXXXXXXX

**Comment by elinz** [comment] 2015-02-17 16:24
@kerryrobinson Thank you. This will help me when I talk to development; in my opinion if the Esri customer care site is generating the .prvc file this way then the software authorization .exe should support it, and currently is not. I will submit this in this weeks' portal holistic.

**Comment by elinz** [comment] 2015-02-19 16:09
@kerryrobinson I checked with the license team and having multiple products in a .prvc file is a known limitation of the SoftwareAuthorization.exe So the only solution currently, is to place the portal authorization number in a separate .prvc file. The fact that the Customer Care site is generating a .prvc that is not supported is an outstanding issue.

@elinz Action item for me is to add a note in the InstallSettings.bat and Install Guide doc that you _MUST_ use a separate .prvc file for server and another one for portal.

**Comment by elinz** [comment] 2015-08-18 15:53
Fixed in Esri\ops-server-config v.next.

**Closed by elinz** 2015-08-18 15:53 UTC
Labels: G - Release Team, Install and Publishing
