### ISSUE TITLE
Using Rasters to Measure Impact of Weather on Military Operations - needs videos posted for Ops Server Release

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#1202] opened 2015-10-06 18:56 UTC
@mfunk -  check email reminder for details of what goes where.

**Comment by mfunk** [comment] 2016-09-08 15:12
@jrweakland @nfeuerstein Is this still a relevant issue?

**Comment by mfunk** [comment] 2016-09-08 18:45
duplicate of #1143.... closing also.

**Closed by mfunk** 2016-09-08 18:45 UTC
Labels: 0 - Backlog, G - Demo Content, G - Military Team
