### ISSUE TITLE
TEM2015 Test 02: Two different FarthestOnCircle GP services are released

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1304] opened 2015-10-13 16:43 UTC
The GUIDs are for the portal items on the dev portal.
Military/FarthestOnCircle.GPServer (779c8029eac24a129ce95a8f4caa8301)
Military/FarthestOnCircleImageService.GPServer (688999e1df1a4b3ca1eaa63996d3b487)

**Comment by jfrygeo** [comment] 2015-10-13 18:26
The Farthest On Circle Image Service ( 688999e1df1a4b3ca1eaa63996d3b487 ) ideally should be the only one released.... It works with an image service, but due to issue #777 it does not work with IWA, so the other service (Military/FarthestOnCircle.GPServer (779c8029eac24a129ce95a8f4caa8301)) was created. I have tried the image service with other OpsServer cuts (at UC) and confirmed that it works with non-IWA configurations. Currently working on issue #777, but will not be resolved until some time in the future. To clarify the issue:

<b>Should be released</b>
<li> Farthest On Circle Image Service GP Tool (688999e1df1a4b3ca1eaa63996d3b487)
<li> Watermask image service (1cc140a34bbe439ab8caf4ff6e172c2c)

<b> Can be removed</b>
<li>Farthest On Circle GP Tool (779c8029eac24a129ce95a8f4caa8301)

**Comment by elinz** [comment] 2015-10-13 20:35
Will we assess what action to be taken for this release.

**Comment by conklinbd** [comment] 2015-10-14 16:03
@jfrygeo does the other service Farthest On Circle GP Tool (779c8029eac24a129ce95a8f4caa8301) not work? Just trying to asses if this is a showstopper or not.

**Comment by elinz** [comment] 2015-10-14 16:26
Let's release both of these GP services with the Fall release in case a customer wants to enable IWA on their Ops Server; in this case they will have a GP service that will work.

**Comment by conklinbd** [comment] 2015-10-14 16:28
Sounds good to me. I will just put this issue for the after-next milestone so we can see if this can be resolved in 10.4.

**Comment by conklinbd** [comment] 2015-10-14 16:28
Actually realized that #777 better captures this issue. I am closing this item.

**Closed by conklinbd** 2015-10-14 16:28 UTC
Labels: 0 - Backlog, B - Bug, G - Military Team
