### ISSUE TITLE
Web map "Monterey Region (Incident Analysis)" references MontereyDistrictBoundaries service that does not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1150] opened 2015-10-02 22:18 UTC
@jrweakland @lfunkhouser Web map "Monterey Region (Incident Analysis)" b83cf730926943bdab17b0b91e9d6d98 which is owned by "DemoMilitary" account contains a reference to the following service that does not exist anymore:
Hosted/MontereyDistrictBoundaries/FeatureServer/0  

The service is now called DistrictBoundaries.

**Comment by conklinbd** [comment] 2015-10-05 14:35
I fixed this issue. This issue was a duplicate of #1150 so I am closing.

**Closed** 2015-10-05 14:35 UTC
Labels: B - Duplicate, G - Military Team
