### ISSUE TITLE
ArcGIS Predictive Analysis Tools - needs slides and videos posted

### ISSUE THREAD

**Issue by dfoll** [Esri/ops-server-config#1140] opened 2015-10-02 21:40 UTC
for Ops Server release
Deadline 9Oct
see email for post location
@rbernstein @kAilshie

**Comment by kAilshie** [comment] 2015-10-02 21:43
@dfoll I think this is a duplicate of #1119

**Comment by dfoll** [comment] 2015-10-02 21:57
pretty much... we will fix that up next... not sure why the previous one got entered

**Comment by ircampbell** [comment] 2015-10-06 16:46
Video, script, and slides have been added here.... 
•	Videos and scripts: \\disldb\OpsServerStaging\2015_Q4\Resources\Videos
•	Presentation here: \\disldb\OpsServerStaging\2015_Q4\Resources\2015UCPresentations

**Comment by ircampbell** [comment] 2015-10-06 16:48
@dfoll Please verify and close

**Comment by dfoll** [comment] 2015-10-07 16:46
@ircampbell thanks

**Closed** 2015-10-07 16:46 UTC
Labels: 0 - Backlog, 3 - Verify, G - Demo Content, G - Intelligence Team
